- platform: limitlessled
  bridges:
    - host: 192.168.2.105
      version: 4
      port: 8899
      groups:
      - number: 1
        name: Regal
        type: rgbw
        fade: on
      - number: 2
        name: Schrank
        type: rgbw
        fade: on
      - number: 3
        name: Weltkarte
        type: rgbw
        fade: on
    - host: 192.168.2.103
      groups:
      - number: 2
        name: Schreibtisch_led
        type: rgbww
      - number: 1
        name: Bett
        type: rgbww
- platform: mqtt
  name: map
  state_topic: "zimmer/map/light/status"
  command_topic: "zimmer/map/light/switch"
  brightness_state_topic: "zimmer/map/brightness/status"
  brightness_command_topic: "zimmer/map/brightness/set"
  rgb_state_topic: "zimmer/map/rgb/status"
  rgb_command_topic: "zimmer/map/rgb/set"
  state_value_template: "{{ value_json.state }}"
  brightness_value_template: "{{ value_json.brightness }}"
  rgb_value_template: "{{ value_json.rgb | join(',') }}"
  effect_command_topic: "zimmer/map/effect/set"
  effect_state_topic: "zimmer/map/effect/status"
  effect_list : [slow, medium, fast]
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: true
- platform: mqtt
  name: project
  state_topic: "zimmer/project/light/status"
  command_topic: "zimmer/project/light/switch"
  brightness_state_topic: "zimmer/project/brightness/status"
  brightness_command_topic: "zimmer/project/brightness/set"
  rgb_state_topic: "zimmer/project/rgb/status"
  rgb_command_topic: "zimmer/project/rgb/set"
  state_value_template: "{{ value_json.state }}"
  brightness_value_template: "{{ value_json.brightness }}"
  rgb_value_template: "{{ value_json.rgb | join(',') }}"
  effect_command_topic: "zimmer/project/effect/set"
  effect_state_topic: "zimmer/project/effect/status"
  effect_list : [slow, medium, fast]
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: true
  schema: json
  brightness: true
  rgb: true
  white_value: true
  white_value_comand_topic: "zimmer/project/white/set"
